# permissions for end users to edit registryfailovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registryfailover-editor-role
rules:
- apiGroups:
  - cache.vologue.dev
  resources:
  - registryfailovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.vologue.dev
  resources:
  - registryfailovers/status
  verbs:
  - get
