# permissions for end users to view registryfailovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registryfailover-viewer-role
rules:
- apiGroups:
  - cache.vologue.dev
  resources:
  - registryfailovers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.vologue.dev
  resources:
  - registryfailovers/status
  verbs:
  - get
