# permissions for end users to view registry-failovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-failover-viewer-role
rules:
- apiGroups:
  - cache.vologue.dev
  resources:
  - registry-failovers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.vologue.dev
  resources:
  - registry-failovers/status
  verbs:
  - get
